### ISSUE TITLE
Project structure 

### ISSUE THREAD

**Issue by AlmeidaJoao** [AlbertoYabeda/dice-game#1]
I would recommend creating a structure to organize your files in your application. This is not an attempt to create any kind of standard. Instead, I will make suggestions on how to group and name files in a logical convenient way.

For a basic project consider the following structure:

![image](https://user-images.githubusercontent.com/39647781/83408874-a357de00-a413-11ea-85bd-b474a010f3b2.png)
Find more at: https://medium.com/@nmayurashok/file-and-folder-structure-for-web-development-8c5c83810a5

![image](https://user-images.githubusercontent.com/39647781/83408945-c5516080-a413-11ea-9771-04840b884c15.png)
Find more at: https://www.codecademy.com/articles/f1-u2-create-first-prj

**Comment by Algy-Jr12** [comment]
I would recommend you to centre well the following elements (text field)  in their respective **div** or **button**. I circled the elements I'm referring to, on the following image. 

<img width="1440" alt="Captura de ecrã 2020-06-01, às 14 08 01" src="https://user-images.githubusercontent.com/52712652/83409496-d189ed80-a414-11ea-86ed-59e5e18ffb55.png">

**Comment by callebdev** [comment]
I totally agree with Almeida!
